---
title: "Corporations Regextable"
author: "Shirlyn Dong"
date: "`r Sys.Date()`"
format: 
  html:
    toc: true
vignette: >
  %\VignetteIndexEntry{Corporations}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache = FALSE,
  warning = FALSE,
  message = FALSE,
  tidy = FALSE,
  fig.align = 'center',
  fig.path = "figures/native-tribes-",
  R.options = list(width = 120)
)

# Format kable tables
kable <- function(x){
  if (knitr::is_latex_output()) {
    head(x, 5) |>
      knitr::kable(booktabs = TRUE, format = 'latex') |>
      kableExtra::kable_styling(latex_options = c("striped", "scale_down", "HOLD_position"))
  } else {
    head(x, 5) |>
      knitr::kable(escape = TRUE) |>
      kableExtra::kable_styling()
  }
}
```

### Introduction


Install and load the package:
```{r, message=FALSE}
library(regextable)
library(kableExtra)
library(rvest)
library(purrr)
library(tibble)
library(stringr)
```



```{r}
data <- read.csv("/Users/shirl/Downloads/corporations_crosswalk.csv", stringsAsFactors = FALSE)
kable(head(data))
```

```{r}
corp_url <- "https://raw.githubusercontent.com/judgelord/corporations/main/data/corporations_data_sample.rda"
tmp <- tempfile(fileext = ".rda")
download.file(corp_url, tmp, mode = "wb")
load(tmp)
regex_table <- corporations_data_sample
rm(corporations_data_sample)
regex_table <- reegx_table %>% select(-FED_RSSD, -naics)
```

